In [ ]:
import os
import numpy as np
import pandas as pd
data = pd.read_csv("pulsar_data.csv")
data.columns




Index([' Mean of the integrated profile',
       ' Standard deviation of the integrated profile',
       ' Excess kurtosis of the integrated profile',
       ' Skewness of the integrated profile', ' Mean of the DM-SNR curve',
       ' Standard deviation of the DM-SNR curve',
       ' Excess kurtosis of the DM-SNR curve', ' Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [ ]:
#unique values in coloumns
print(data[' Mean of the integrated profile'].unique())
print(data[ ' Standard deviation of the integrated profile'].unique())
print(data[' Excess kurtosis of the integrated profile'].unique())
print(data[' Skewness of the integrated profile'].unique())
print(data[' Mean of the DM-SNR curve'].unique())
print(data[' Standard deviation of the DM-SNR curve'].unique())
print(data[' Excess kurtosis of the DM-SNR curve'].unique())
print(data[' Skewness of the DM-SNR curve'].unique())
print(data['target_class'].unique())

[121.15625    76.96875   130.5859375 ... 115.375      90.5703125
 135.6640625]
[48.37297113 36.17555664 53.22953353 ... 43.21384643 49.93374944
 50.47225643]
[ 0.37548466  0.71289786  0.13340829 ...  0.66345569 -0.08994031
  0.34617808]
[-0.01316549  3.38871856 -0.29724164 ...  0.43308797 -0.22672618
  0.18479723]
[  3.16889632   2.39966555   2.74331104 ... 152.4197324    7.18645485
   6.14046823]
[18.3993666  17.57099693 22.36255299 ... 11.62814941 21.50150499
 11.79260254]
[ 7.44987415  9.41465226  8.50836378 ... 17.05521452  7.3983949
 17.66222194]
[ 65.15929771 102.7229747   74.0313242  ... 312.2043252   62.33401752
 329.5480159 ]
[0. 1.]


In [ ]:
#Basic preprocessing

#handling missing values
data.isna().sum()

 Mean of the integrated profile                     0
 Standard deviation of the integrated profile       0
 Excess kurtosis of the integrated profile       1735
 Skewness of the integrated profile                 0
 Mean of the DM-SNR curve                           0
 Standard deviation of the DM-SNR curve          1178
 Excess kurtosis of the DM-SNR curve                0
 Skewness of the DM-SNR curve                     625
target_class                                        0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(fill_value=np.nan, strategy='mean')
X = imputer.fit_transform(data)
data = pd.DataFrame(X, columns=data.columns)

print(data)

        Mean of the integrated profile  ...  target_class
0                           121.156250  ...           0.0
1                            76.968750  ...           0.0
2                           130.585938  ...           0.0
3                           156.398438  ...           0.0
4                            84.804688  ...           0.0
...                                ...  ...           ...
12523                       124.312500  ...           0.0
12524                       115.617188  ...           0.0
12525                       116.031250  ...           0.0
12526                       135.664062  ...           0.0
12527                       120.726562  ...           0.0

[12528 rows x 9 columns]


In [ ]:
data.isna().sum()

 Mean of the integrated profile                  0
 Standard deviation of the integrated profile    0
 Excess kurtosis of the integrated profile       0
 Skewness of the integrated profile              0
 Mean of the DM-SNR curve                        0
 Standard deviation of the DM-SNR curve          0
 Excess kurtosis of the DM-SNR curve             0
 Skewness of the DM-SNR curve                    0
target_class                                     0
dtype: int64

In [ ]:
# Data splitting 
from sklearn.model_selection import train_test_split
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                                    random_state=101)


STEP :1   
APPLYING ALGORITHMS WITHOUT ANY PREPROCESSING

In [ ]:
#Score function we gonna use
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, roc_auc_score
def print_score(clf, X_train, X_test, y_train, y_test, train=True):
    '''
    v0.1 Follow the scikit learn library format in terms of input
    print the accuracy score, classification report and confusion matrix of classifier
    '''
    lb = preprocessing.LabelBinarizer()
    lb.fit(y_train)
    if train:
        '''
        training performance
        '''
        res = clf.predict(X_train)
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, 
                                                                res)))
        print("Classification Report: \n {}\n".format(classification_report(y_train, 
                                                                            res)))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, 
                                                                  res)))
        print("ROC AUC: {0:.4f}\n".format(roc_auc_score(lb.transform(y_train), 
                                                      lb.transform(res))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        test performance
        '''
        res_test = clf.predict(X_test)
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, 
                                                                res_test)))
        print("Classification Report: \n {}\n".format(classification_report(y_test, 
                                                                            res_test)))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, 
                                                                  res_test)))   
        print("ROC AUC: {0:.4f}\n".format(roc_auc_score(lb.transform(y_test), 
                                                      lb.transform(res_test))))

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9754

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      9090
         1.0       0.93      0.80      0.86       932

    accuracy                           0.98     10022
   macro avg       0.95      0.90      0.92     10022
weighted avg       0.97      0.98      0.97     10022


Confusion Matrix: 
 [[9031   59]
 [ 188  744]]

ROC AUC: 0.8959

Average Accuracy: 	 0.9707
Accuracy SD: 		 0.0060


In [ ]:
#XG BOOSTING
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(X_train, y_train)
print_score(model, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9819

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.99      1.00      0.99      9090
         1.0       0.95      0.85      0.90       932

    accuracy                           0.98     10022
   macro avg       0.97      0.92      0.94     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9045   45]
 [ 136  796]]

ROC AUC: 0.9246

Average Accuracy: 	 0.9782
Accuracy SD: 		 0.0048


In [ ]:
#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9246

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.89      0.96      0.93       908
         1.0       0.96      0.89      0.92       936

    accuracy                           0.92      1844
   macro avg       0.93      0.93      0.92      1844
weighted avg       0.93      0.92      0.92      1844


Confusion Matrix: 
 [[876  32]
 [107 829]]

ROC AUC: 0.9252

Average Accuracy: 	 0.9235
Accuracy SD: 		 0.0198


In [ ]:
#Random Forest Classifier 
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9772

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      9090
         1.0       0.94      0.80      0.87       932

    accuracy                           0.98     10022
   macro avg       0.96      0.90      0.93     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9045   45]
 [ 184  748]]

ROC AUC: 0.8988

Average Accuracy: 	 0.9757
Accuracy SD: 		 0.0053


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)


Train Result:

accuracy score: 0.9436

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.95      0.97      9090
         1.0       0.65      0.84      0.74       932

    accuracy                           0.94     10022
   macro avg       0.82      0.90      0.85     10022
weighted avg       0.95      0.94      0.95     10022


Confusion Matrix: 
 [[8672  418]
 [ 147  785]]

ROC AUC: 0.8981

Average Accuracy: 	 0.9435
Accuracy SD: 		 0.0064


STEP : 2 
USING DIFFERENT WAYS TO HANDLE MISSING VALUES AND ITS OBSERVATIONS
A) droping rows, 
B) replacing with median, 
C) replacing with mode, 

In [ ]:
#1 DROP NA
import os
import numpy as np
import pandas as pd
data = pd.read_csv("pulsar_data.csv")
data.isna().sum()


 Mean of the integrated profile                     0
 Standard deviation of the integrated profile       0
 Excess kurtosis of the integrated profile       1735
 Skewness of the integrated profile                 0
 Mean of the DM-SNR curve                           0
 Standard deviation of the DM-SNR curve          1178
 Excess kurtosis of the DM-SNR curve                0
 Skewness of the DM-SNR curve                     625
target_class                                        0
dtype: int64

In [ ]:
data.dropna(inplace = True)
data.isna().sum()

 Mean of the integrated profile                  0
 Standard deviation of the integrated profile    0
 Excess kurtosis of the integrated profile       0
 Skewness of the integrated profile              0
 Mean of the DM-SNR curve                        0
 Standard deviation of the DM-SNR curve          0
 Excess kurtosis of the DM-SNR curve             0
 Skewness of the DM-SNR curve                    0
target_class                                     0
dtype: int64

In [ ]:
# Data splitting 
from sklearn.model_selection import train_test_split
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                                    random_state=101)

In [ ]:
#RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9807

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      6747
         1.0       0.94      0.84      0.89       671

    accuracy                           0.98      7418
   macro avg       0.96      0.92      0.94      7418
weighted avg       0.98      0.98      0.98      7418


Confusion Matrix: 
 [[6711   36]
 [ 107  564]]

ROC AUC: 0.9176

Average Accuracy: 	 0.9798
Accuracy SD: 		 0.0044


In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)


Train Result:

accuracy score: 0.9787

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      6747
         1.0       0.94      0.82      0.87       671

    accuracy                           0.98      7418
   macro avg       0.96      0.91      0.93      7418
weighted avg       0.98      0.98      0.98      7418


Confusion Matrix: 
 [[6710   37]
 [ 121  550]]

ROC AUC: 0.9071

Average Accuracy: 	 0.9726
Accuracy SD: 		 0.0058


In [ ]:
#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9737

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      6747
         1.0       0.95      0.75      0.84       671

    accuracy                           0.97      7418
   macro avg       0.96      0.87      0.91      7418
weighted avg       0.97      0.97      0.97      7418


Confusion Matrix: 
 [[6718   29]
 [ 166  505]]

ROC AUC: 0.8742

Average Accuracy: 	 0.9734
Accuracy SD: 		 0.0054


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9458

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.96      0.97      6747
         1.0       0.65      0.85      0.74       671

    accuracy                           0.95      7418
   macro avg       0.82      0.90      0.85      7418
weighted avg       0.95      0.95      0.95      7418


Confusion Matrix: 
 [[6444  303]
 [  99  572]]

ROC AUC: 0.9038

Average Accuracy: 	 0.9459
Accuracy SD: 		 0.0057


In [ ]:
#2 SIMPLEIMPUTER (MEDIAN)
import os
import numpy as np
import pandas as pd
data = pd.read_csv("pulsar_data.csv")


In [ ]:
data.isna().sum()

 Mean of the integrated profile                     0
 Standard deviation of the integrated profile       0
 Excess kurtosis of the integrated profile       1735
 Skewness of the integrated profile                 0
 Mean of the DM-SNR curve                           0
 Standard deviation of the DM-SNR curve          1178
 Excess kurtosis of the DM-SNR curve                0
 Skewness of the DM-SNR curve                     625
target_class                                        0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(fill_value=np.nan, strategy='median')
X = imputer.fit_transform(data)
data = pd.DataFrame(X, columns=data.columns)
data.isna().sum()

 Mean of the integrated profile                  0
 Standard deviation of the integrated profile    0
 Excess kurtosis of the integrated profile       0
 Skewness of the integrated profile              0
 Mean of the DM-SNR curve                        0
 Standard deviation of the DM-SNR curve          0
 Excess kurtosis of the DM-SNR curve             0
 Skewness of the DM-SNR curve                    0
target_class                                     0
dtype: int64

In [ ]:
# Data splitting 
from sklearn.model_selection import train_test_split
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                                    random_state=101)

In [ ]:
#RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9772

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      9090
         1.0       0.94      0.80      0.87       932

    accuracy                           0.98     10022
   macro avg       0.96      0.90      0.93     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9045   45]
 [ 184  748]]

ROC AUC: 0.8988

Average Accuracy: 	 0.9759
Accuracy SD: 		 0.0052


In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9755

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      9090
         1.0       0.93      0.80      0.86       932

    accuracy                           0.98     10022
   macro avg       0.95      0.90      0.92     10022
weighted avg       0.97      0.98      0.97     10022


Confusion Matrix: 
 [[9033   57]
 [ 189  743]]

ROC AUC: 0.8955

Average Accuracy: 	 0.9707
Accuracy SD: 		 0.0058


In [ ]:
#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9703

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      9090
         1.0       0.94      0.73      0.82       932

    accuracy                           0.97     10022
   macro avg       0.96      0.86      0.90     10022
weighted avg       0.97      0.97      0.97     10022


Confusion Matrix: 
 [[9046   44]
 [ 254  678]]

ROC AUC: 0.8613

Average Accuracy: 	 0.9701
Accuracy SD: 		 0.0055


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9433

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.95      0.97      9090
         1.0       0.65      0.85      0.74       932

    accuracy                           0.94     10022
   macro avg       0.82      0.90      0.85     10022
weighted avg       0.95      0.94      0.95     10022


Confusion Matrix: 
 [[8665  425]
 [ 143  789]]

ROC AUC: 0.8999

Average Accuracy: 	 0.9434
Accuracy SD: 		 0.0070


In [ ]:
#3 SIMPLEIMPUTER (MODE)
import os
import numpy as np
import pandas as pd
data = pd.read_csv("pulsar_data.csv")


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(fill_value=np.nan, strategy='most_frequent')
X = imputer.fit_transform(data)
data = pd.DataFrame(X, columns=data.columns)
data.isna().sum()

 Mean of the integrated profile                  0
 Standard deviation of the integrated profile    0
 Excess kurtosis of the integrated profile       0
 Skewness of the integrated profile              0
 Mean of the DM-SNR curve                        0
 Standard deviation of the DM-SNR curve          0
 Excess kurtosis of the DM-SNR curve             0
 Skewness of the DM-SNR curve                    0
target_class                                     0
dtype: int64

In [ ]:
# Data splitting 
from sklearn.model_selection import train_test_split
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                                    random_state=101)

In [ ]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9771

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      9090
         1.0       0.94      0.80      0.87       932

    accuracy                           0.98     10022
   macro avg       0.96      0.90      0.93     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9044   46]
 [ 184  748]]

ROC AUC: 0.8988

Average Accuracy: 	 0.9759
Accuracy SD: 		 0.0055


In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9757

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      9090
         1.0       0.93      0.80      0.86       932

    accuracy                           0.98     10022
   macro avg       0.95      0.90      0.92     10022
weighted avg       0.97      0.98      0.97     10022


Confusion Matrix: 
 [[9033   57]
 [ 187  745]]

ROC AUC: 0.8965

Average Accuracy: 	 0.9709
Accuracy SD: 		 0.0062


In [ ]:
#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9694

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      9090
         1.0       0.94      0.72      0.81       932

    accuracy                           0.97     10022
   macro avg       0.96      0.86      0.90     10022
weighted avg       0.97      0.97      0.97     10022


Confusion Matrix: 
 [[9046   44]
 [ 263  669]]

ROC AUC: 0.8565

Average Accuracy: 	 0.9691
Accuracy SD: 		 0.0055


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9434

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.96      0.97      9090
         1.0       0.66      0.82      0.73       932

    accuracy                           0.94     10022
   macro avg       0.82      0.89      0.85     10022
weighted avg       0.95      0.94      0.95     10022


Confusion Matrix: 
 [[8692  398]
 [ 169  763]]

ROC AUC: 0.8874

Average Accuracy: 	 0.9432
Accuracy SD: 		 0.0080


STEP :3 HANDLING IMBALANCED DATASET USING RANDOM SAMPLING



In [ ]:
#RANDOM OVER SAMPLER
import os
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from sklearn.impute import SimpleImputer
data = pd.read_csv("pulsar_data.csv")
imputer = SimpleImputer(fill_value=np.nan, strategy='mean')
X = imputer.fit_transform(data)
data = pd.DataFrame(X, columns=data.columns)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
print(Counter(y))
oversample = RandomOverSampler(sampling_strategy='minority') #OVER SAMPLING
x,y = oversample.fit_resample(x, y)
print(Counter(y))



Counter({0.0: 11375, 1.0: 1153})
Counter({0.0: 11375, 1.0: 11375})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                                    random_state=101)

In [ ]:
#RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9364

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.90      0.97      0.94      9060
         1.0       0.97      0.90      0.93      9140

    accuracy                           0.94     18200
   macro avg       0.94      0.94      0.94     18200
weighted avg       0.94      0.94      0.94     18200


Confusion Matrix: 
 [[8833  227]
 [ 930 8210]]

ROC AUC: 0.9366

Average Accuracy: 	 0.9358
Accuracy SD: 		 0.0071


In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9786

Classification Report: 
               precision    recall  f1-score   support

         0.0       1.00      0.96      0.98      9060
         1.0       0.96      1.00      0.98      9140

    accuracy                           0.98     18200
   macro avg       0.98      0.98      0.98     18200
weighted avg       0.98      0.98      0.98     18200


Confusion Matrix: 
 [[8677  383]
 [   7 9133]]

ROC AUC: 0.9785

Average Accuracy: 	 0.9664
Accuracy SD: 		 0.0031


In [ ]:
#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9219

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.89      0.97      0.93      9060
         1.0       0.96      0.88      0.92      9140

    accuracy                           0.92     18200
   macro avg       0.93      0.92      0.92     18200
weighted avg       0.93      0.92      0.92     18200


Confusion Matrix: 
 [[8767  293]
 [1128 8012]]

ROC AUC: 0.9221

Average Accuracy: 	 0.9216
Accuracy SD: 		 0.0058


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.8997

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.87      0.95      0.90      9060
         1.0       0.94      0.85      0.90      9140

    accuracy                           0.90     18200
   macro avg       0.90      0.90      0.90     18200
weighted avg       0.90      0.90      0.90     18200


Confusion Matrix: 
 [[8562  498]
 [1328 7812]]

ROC AUC: 0.8999

Average Accuracy: 	 0.8996
Accuracy SD: 		 0.0076


In [ ]:
#RANDOM UNDER SAMPLER
import os
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.under_sampling import RandomUnderSampler
from sklearn.impute import SimpleImputer
data = pd.read_csv("pulsar_data.csv")
imputer = SimpleImputer(fill_value=np.nan, strategy='mean')
X = imputer.fit_transform(data)
data = pd.DataFrame(X, columns=data.columns)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
print(Counter(y))
undersample = RandomUnderSampler(sampling_strategy='majority')
x,y = undersample.fit_resample(x, y)
print(Counter(y))


Counter({0.0: 11375, 1.0: 1153})
Counter({0.0: 1153, 1.0: 1153})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                                    random_state=101)

In [ ]:
#Random Forest Classifier 
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9393

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.91      0.97      0.94       908
         1.0       0.97      0.90      0.94       936

    accuracy                           0.94      1844
   macro avg       0.94      0.94      0.94      1844
weighted avg       0.94      0.94      0.94      1844


Confusion Matrix: 
 [[885  23]
 [ 89 847]]

ROC AUC: 0.9398

Average Accuracy: 	 0.9300
Accuracy SD: 		 0.0122


In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9290

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.91      0.95      0.93       908
         1.0       0.95      0.91      0.93       936

    accuracy                           0.93      1844
   macro avg       0.93      0.93      0.93      1844
weighted avg       0.93      0.93      0.93      1844


Confusion Matrix: 
 [[862  46]
 [ 85 851]]

ROC AUC: 0.9293

Average Accuracy: 	 0.9105
Accuracy SD: 		 0.0197


In [ ]:
#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9203

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.89      0.96      0.92       908
         1.0       0.96      0.88      0.92       936

    accuracy                           0.92      1844
   macro avg       0.92      0.92      0.92      1844
weighted avg       0.92      0.92      0.92      1844


Confusion Matrix: 
 [[874  34]
 [113 823]]

ROC AUC: 0.9209

Average Accuracy: 	 0.9176
Accuracy SD: 		 0.0202


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.8948

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.86      0.94      0.90       908
         1.0       0.93      0.85      0.89       936

    accuracy                           0.89      1844
   macro avg       0.90      0.90      0.89      1844
weighted avg       0.90      0.89      0.89      1844


Confusion Matrix: 
 [[851  57]
 [137 799]]

ROC AUC: 0.8954

Average Accuracy: 	 0.8942
Accuracy SD: 		 0.0212


STEP :4 HANDLING NOISY DATA BY NORMALIZTION 

In [ ]:
#NORMALIZATION
#MIN MAX SCALER
import os
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
data = pd.read_csv("pulsar_data.csv")
imputer = SimpleImputer(fill_value=np.nan, strategy='mean')
X = imputer.fit_transform(data)
data = pd.DataFrame(X, columns=data.columns)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                              random_state=101)
norm=MinMaxScaler().fit(X_train)
X_train=norm.transform(X_train)
X_test=norm.transform(X_test)
 
print(X_train)




[[0.64217144 0.40259083 0.18862545 ... 0.18379548 0.32306238 0.09011295]
 [0.46453148 0.24450447 0.22600651 ... 0.08077717 0.30704202 0.07676862]
 [0.5013168  0.29945691 0.24341853 ... 0.12131752 0.27118817 0.05032739]
 ...
 [0.52476425 0.27105388 0.20674425 ... 0.0472555  0.44866096 0.18349069]
 [0.07187155 0.12802119 0.73344116 ... 0.49995615 0.11465779 0.00276305]
 [0.63006542 0.32770201 0.19298879 ... 0.10813738 0.31908926 0.07712337]]


In [ ]:
#RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9772

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      9090
         1.0       0.94      0.80      0.87       932

    accuracy                           0.98     10022
   macro avg       0.96      0.90      0.93     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9045   45]
 [ 184  748]]

ROC AUC: 0.8988

Average Accuracy: 	 0.9757
Accuracy SD: 		 0.0053


In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9782

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      9090
         1.0       0.94      0.82      0.88       932

    accuracy                           0.98     10022
   macro avg       0.96      0.91      0.93     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9037   53]
 [ 165  767]]

ROC AUC: 0.9086

Average Accuracy: 	 0.9753
Accuracy SD: 		 0.0040


In [ ]:
#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9764

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      9090
         1.0       0.95      0.79      0.86       932

    accuracy                           0.98     10022
   macro avg       0.96      0.89      0.92     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9050   40]
 [ 197  735]]

ROC AUC: 0.8921

Average Accuracy: 	 0.9756
Accuracy SD: 		 0.0053


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9436

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.95      0.97      9090
         1.0       0.65      0.84      0.74       932

    accuracy                           0.94     10022
   macro avg       0.82      0.90      0.85     10022
weighted avg       0.95      0.94      0.95     10022


Confusion Matrix: 
 [[8672  418]
 [ 147  785]]

ROC AUC: 0.8981

Average Accuracy: 	 0.9435
Accuracy SD: 		 0.0064


In [ ]:
#STANDARDIZATION

import os
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
data = pd.read_csv("pulsar_data.csv")
imputer = SimpleImputer(fill_value=np.nan, strategy='mean')
X = imputer.fit_transform(data)
data = pd.DataFrame(X, columns=data.columns)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                              random_state=101)
print(X_train)




                0          1         2  ...          5          6           7
4331   123.921875  51.760357  0.111931  ...  26.351318   9.033435  105.525779
10688   91.250000  41.162787  0.478548  ...  15.712434   8.429801   89.606289
12183   98.015625  44.846611  0.649317  ...  19.899108   7.078860   58.062486
8398   143.257812  52.446885 -0.071339  ...  46.690946   3.367872    9.980539
6015    84.773438  40.689797  0.763434  ...  36.351589   3.975499   15.625425
...           ...        ...       ...  ...        ...        ...         ...
599    110.812500  51.641455  0.346589  ...  19.983003   6.547905   50.614000
5695   107.398438  42.822917  0.478548  ...  21.874631   7.710425   63.850019
8006   102.328125  42.942569  0.289632  ...  12.250591  13.765878  216.923344
1361    19.031250  33.354146  5.455235  ...  59.001793   1.180934    1.319287
1547   121.695312  46.740066  0.154725  ...  18.537972   8.883731   90.029494

[10022 rows x 8 columns]


In [ ]:
for i in range(8):
    
    # fit on training data column
    scale = StandardScaler().fit(X_train[[i]])
    
    # transform the training data column
    X_train[i] = scale.transform(X_train[[i]])
    
    # transform the testing data column
    X_test[i] = scale.transform(X_test[[i]])

print(X_train)

              0         1         2  ...         5         6         7
4331   0.502247  0.773050 -0.372960  ... -0.003053  0.160980  0.006487
10688 -0.761821 -0.784411 -0.002802  ... -0.574069  0.027270 -0.148678
12183 -0.500060 -0.243022  0.169617  ... -0.349360 -0.271977 -0.456132
8398   1.250350  0.873944 -0.558002  ...  1.088627 -1.093999 -0.924780
6015  -1.012397 -0.853923  0.284836  ...  0.533687 -0.959403 -0.869760
...         ...       ...       ...  ...       ...       ...       ...
599   -0.004952  0.755575 -0.136036  ... -0.344857 -0.389589 -0.528731
5695  -0.137041 -0.540432 -0.002802  ... -0.243328 -0.132080 -0.399721
8006  -0.333210 -0.522847 -0.193543  ... -0.759875  1.209264  1.092265
1361  -3.555948 -1.931999  5.021966  ...  1.749381 -1.578427 -1.009201
1547   0.416102  0.035248 -0.329753  ... -0.422415  0.127820 -0.144553

[10022 rows x 8 columns]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats

In [ ]:
#RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9772

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      9090
         1.0       0.94      0.80      0.87       932

    accuracy                           0.98     10022
   macro avg       0.96      0.90      0.93     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9045   45]
 [ 184  748]]

ROC AUC: 0.8988

Average Accuracy: 	 0.9757
Accuracy SD: 		 0.0053


In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9790

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      9090
         1.0       0.94      0.83      0.88       932

    accuracy                           0.98     10022
   macro avg       0.96      0.91      0.93     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9040   50]
 [ 160  772]]

ROC AUC: 0.9114

Average Accuracy: 	 0.9758
Accuracy SD: 		 0.0045


In [ ]:
#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9787

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      9090
         1.0       0.95      0.81      0.88       932

    accuracy                           0.98     10022
   macro avg       0.97      0.90      0.93     10022
weighted avg       0.98      0.98      0.98     10022


Confusion Matrix: 
 [[9050   40]
 [ 173  759]]

ROC AUC: 0.9050

Average Accuracy: 	 0.9776
Accuracy SD: 		 0.0047


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9436

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.95      0.97      9090
         1.0       0.65      0.84      0.74       932

    accuracy                           0.94     10022
   macro avg       0.82      0.90      0.85     10022
weighted avg       0.95      0.94      0.95     10022


Confusion Matrix: 
 [[8672  418]
 [ 147  785]]

ROC AUC: 0.8981

Average Accuracy: 	 0.9435
Accuracy SD: 		 0.0064


PERFORMING RANDOM FOREST CLASSIFIER WITH BEST PREPOCESSING TECHNIQUES

In [ ]:
import os
import numpy as np
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
data = pd.read_csv("pulsar_data.csv")
data.dropna(inplace = True)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
undersample = RandomUnderSampler(sampling_strategy='majority')
x,y = undersample.fit_resample(x, y)
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                              random_state=101)
norm=MinMaxScaler().fit(X_train)
X_train=norm.transform(X_train)
X_test=norm.transform(X_test)

from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf=rmf.fit(X_train, y_train)
print_score(rmf, X_train, X_test, y_train, y_test, train=True)

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


Train Result:

accuracy score: 0.9382

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.90      0.98      0.94       678
         1.0       0.98      0.90      0.94       682

    accuracy                           0.94      1360
   macro avg       0.94      0.94      0.94      1360
weighted avg       0.94      0.94      0.94      1360


Confusion Matrix: 
 [[665  13]
 [ 71 611]]

ROC AUC: 0.9384

Average Accuracy: 	 0.9316
Accuracy SD: 		 0.0195


PERFORMING KNN ALGORITHM WITH BEST PREPOCESSING TECHNIQUES

In [ ]:
import os
import numpy as np
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
data = pd.read_csv("pulsar_data.csv")
data.dropna(inplace = True)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
oversample = RandomOverSampler(sampling_strategy='minority') #OVER SAMPLING
x,y = oversample.fit_resample(x, y)

X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                              random_state=101)
for i in range(8):
    
    # fit on training data column
    scale = StandardScaler().fit(X_train[[i]])
    
    # transform the training data column
    X_train[i] = scale.transform(X_train[[i]])
    
    # transform the testing data column
    X_test[i] = scale.transform(X_test[[i]])


#KNN
from sklearn.neighbors import KNeighborsClassifier 
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf=knn_clf.fit(X_train, y_train) 
print_score(knn_clf, X_train, X_test, y_train, y_test, train=True)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


Train Result:

accuracy score: 0.9782

Classification Report: 
               precision    recall  f1-score   support

         0.0       1.00      0.96      0.98      6733
         1.0       0.96      1.00      0.98      6743

    accuracy                           0.98     13476
   macro avg       0.98      0.98      0.98     13476
weighted avg       0.98      0.98      0.98     13476


Confusion Matrix: 
 [[6445  288]
 [   6 6737]]

ROC AUC: 0.9782

Average Accuracy: 	 0.9656
Accuracy SD: 		 0.0042


PERFORMING SVM ALGORITHM WITH BEST PREPOCESSING TECHNIQUES

In [ ]:
import os
import numpy as np
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
data = pd.read_csv("pulsar_data.csv")
data.dropna(inplace = True)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
undersample = RandomUnderSampler(sampling_strategy='majority')
x,y = undersample.fit_resample(x, y)
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                              random_state=101)
for i in range(8):
    
    # fit on training data column
    scale = StandardScaler().fit(X_train[[i]])
    
    # transform the training data column
    X_train[i] = scale.transform(X_train[[i]])
    
    # transform the testing data column
    X_test[i] = scale.transform(X_test[[i]])

#SVM 
from sklearn import svm
sv = svm.SVC()
sv=sv.fit(X_train, y_train)
print_score(sv, X_train, X_test, y_train, y_test, train=True)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


Train Result:

accuracy score: 0.9176

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.89      0.96      0.92       678
         1.0       0.95      0.88      0.91       682

    accuracy                           0.92      1360
   macro avg       0.92      0.92      0.92      1360
weighted avg       0.92      0.92      0.92      1360


Confusion Matrix: 
 [[648  30]
 [ 82 600]]

ROC AUC: 0.9178

Average Accuracy: 	 0.9125
Accuracy SD: 		 0.0149


PERFORMING NAIVE BAYES CLASSIFICATION ALGORITHM WITH BEST PREPOCESSING TECHNIQUES

In [ ]:
import os
import numpy as np
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
data = pd.read_csv("pulsar_data.csv")
data.dropna(inplace = True)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x = pd.DataFrame(x)
y = pd.Series(y)
oversample = RandomOverSampler(sampling_strategy='minority') #OVER SAMPLING
x,y = oversample.fit_resample(x, y)

X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                              random_state=101)
for i in range(8):
    
    # fit on training data column
    scale = StandardScaler().fit(X_train[[i]])
    
    # transform the training data column
    X_train[i] = scale.transform(X_train[[i]])
    
    # transform the testing data column
    X_test[i] = scale.transform(X_test[[i]])

#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb=nb.fit(X_train, y_train)
print_score(nb, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9043

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.87      0.95      0.91      6733
         1.0       0.94      0.86      0.90      6743

    accuracy                           0.90     13476
   macro avg       0.91      0.90      0.90     13476
weighted avg       0.91      0.90      0.90     13476


Confusion Matrix: 
 [[6367  366]
 [ 923 5820]]

ROC AUC: 0.9044

Average Accuracy: 	 0.9038
Accuracy SD: 		 0.0067


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
